spring.application.name=delivery-planner

spring.datasource.url=jdbc:postgresql://localhost:5433/delivery_planner
spring.datasource.username=postgres
spring.datasource.password=0710nopwPSQL?

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true